Make the nic3com code check how many supported NICs are found
If we find multiple ones, abort with a message to the user, suggesting to use
the flashrom -p nic3com=bb:dd.f syntax. If exactly one supported NIC is found,
use it. If none is found, abort with an error. Print the bb:dd.f numbers for
all supported NICs we find, so the user doesn't have to poke around in lspci
output to find the desired bb:dd.f. Also, drop one pci_read_long() in favor
of using the already existing base_addr[0] struct field. Drop the BAR in user
messages, it's not really useful for us. Instead, explain the BDF syntax a bit
more verbosely. While I'm at it, update the manpage some more to mention and
fully document the external programmer support we have (or will have soon).
The patch is tested on hardware: $ flashrom -p nic3com flashrom v0.9.0-r512
Found NIC "3COM 3C905C: EtherLink 10/100 PCI (TX)" (10b7:9200, BDF 05:04.0)
Found NIC "3COM 3C905C: EtherLink 10/100 PCI (TX)" (10b7:9200, BDF 05:03.0)
Error: Multiple supported NICs found. Please use 'flashrom -p nic3com=bb:dd.f'
to explicitly select the card with the given BDF (PCI bus, device, function).
$ flashrom -p nic3com=05:04.0 flashrom v0.9.0-r512 Found NIC "3COM 3C905C:
EtherLink 10/100 PCI (TX)" (10b7:9200, BDF 05:04.0) Calibrating delay loop...
OK. Found chip "Atmel AT49BV512" (64 KB) at physical address 0xffff0000.
No operations were specified.

Corresponding to flashrom svn r513.

Signed-off-by: Uwe Hermann <uwe@hermann-uwe.de>
Acked-by: Carl-Daniel Hailfinger <c-d.hailfinger.devel.2006@gmx.net>